(in-package :utils)
(defmacro abbrev (short long)
  `(defmacro ,short (&rest args)
     `(,',long ,@args)))
(abbrev mvbind multiple-value-bind)
(abbrev dbind destructuring-bind)
(defun remove-after (item list &key (test #'eql))
  (subseq list (search (list item) list :test test)))
(defun nth-digit (digit number base)
  (if (= 0 digit)
      (mod number base)
      (nth-digit (1- digit) (floor number base) base)))
